### ISSUE TITLE
Cant compile this into a working plugin just get errors all the time .

### ISSUE THREAD

**Issue by SeatloN** [MitchDizzle/PaintBall#2]
paintball.sp
H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\paintball.sp(4) : fatal error 183: cannot read from file: "WeaponAttachmentAPI"
Done

**Comment by MitchDizzle** [comment]
You'll want to build the dev branch: https://github.com/MitchDizzle/PaintBall/tree/dev
Also you will need the weapon attachment api include here: https://github.com/MitchDizzle/WeaponAttachmentAPI

**Comment by SeatloN** [comment]
Now when i use the last you uploaded this is what i get in the compiler.

// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(99) : error 010: invalid function or declaration
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(105) : error 010: invalid function or declaration
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(111) : error 010: invalid function or declaration
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(117) : error 010: invalid function or declaration
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(122) : error 010: invalid function or declaration
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(125) : error 010: invalid function or declaration
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(128) : error 010: invalid function or declaration
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(131) : error 010: invalid function or declaration
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(187) : warning 237: coercing functions to and from primitives is unsupported and will be removed in the future
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(198) : warning 237: coercing functions to and from primitives is unsupported and will be removed in the future
// H:\SERVERTEST\SNG #1\csgo\addons\sourcemod\scripting\include\DHooks.inc(210) : warning 237: coercing functions to and from primitives is unsupported and will be removed in the future

**Comment by SeatloN** [comment]
Well solved the problem with dhooks.inc but i dont get a .smx file when i compile

**Comment by MitchDizzle** [comment]
I went ahead and pushed a commit not including DHook's include file. However i'm not sure why you're not able to get the compiled source out of the compiler.
Edit: I've added a compiled binary under the plugins directory: https://github.com/MitchDizzle/PaintBall/tree/dev/sourcemod

**Comment by SeatloN** [comment]
Thank you soo much ! 
Now i just need to evaluate the plugin with some more ppl !
